#define ALLOW_MULTIPLE_CONNECTIONS      ("AT+CIPMUX=1\r\n")
#define START_SERVER                    ("AT+CIPSERVER=1,4666\r\n")
#define SSID_COMMAND                    ("AT+CWJAP?\r\n")
#define IP_COMMAND                      ("AT+CIFSR\r\n")
#define OK_RESPONSE                     ("OK\r\n")
#define BOOT_RESPONSE                   ("WIFI GOT IP\r\n")
#define SSID_RESPONSE                   ("+CWJAP:")
#define IP_RESPONSE                     ("+CIFSR:STAIP,")
#define SSID_RESPONSE_LEN               (7)
#define IP_RESPONSE_LEN                 (13)
#define BOOT_UP                         ('B')
#define CIPMUX_Tx                       ('M')
#define CIPMUX_Rx                       ('m')
#define CIPSERVER_Tx                    ('S')
#define CIPSERVER_Rx                    ('s')
#define IOT_SETUP_FINISHED              ('F')
#define GET_SSID_Tx                     ('N')
#define GET_SSID_Rx                     ('n')
#define GET_IP_Tx                       ('I')
#define GET_IP_Rx                       ('i')
#define SSID_LEN                        (10)
#define IP_LEN                          (13)

int Init_IOT(void);